const USER_STORAGE = '@pitStop360:user';
const AUTH_TOKEN_STORAGE = '@pitStop360:token';
const VEHICLE_ID_STORAGE = '@pitStop360:vehicle';
const DRIVERS_LICENSE_ID_STORAGE = '@pitStop360:driversLicense';

export { USER_STORAGE, AUTH_TOKEN_STORAGE, VEHICLE_ID_STORAGE, DRIVERS_LICENSE_ID_STORAGE};